### ISSUE TITLE
Block announcement validation errored

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#188] opened 2020-08-08 04:37 UTC
**Traceback**

```
2020-08-08 07:33:43 💔 Block announcement validation errored: UnknownBlock: 0x0997…6084
2020-08-08 07:33:44 💤 [Parachain] Idle (1 peers), best: #64 (0x6f4c…d715), finalized #0 (0xcf5c…5b75), ⬇ 7.3kiB/s ⬆ 3.1kiB/s
2020-08-08 07:33:44 ✨ [Relaychain] Imported #7622 (0x0997…6084)
2020-08-08 07:33:44 💤 [Relaychain] Idle (1 peers), best: #7622 (0x0997…6084), finalized #7613 (0xe262…abd9), ⬇ 8.6kiB/s ⬆ 4.3kiB/s
2020-08-08 07:33:49 💔 Block announcement validation errored: UnknownBlock: 0xedee…cd52
2020-08-08 07:33:49 💤 [Parachain] Idle (1 peers), best: #64 (0x6f4c…d715), finalized #0 (0xcf5c…5b75), ⬇ 7.9kiB/s ⬆ 5.6kiB/s
2020-08-08 07:33:49 💤 [Relaychain] Idle (3 peers), best: #7622 (0x0997…6084), finalized #7620 (0x69fc…f3d6), ⬇ 10.6kiB/s ⬆ 8.5kiB/s
2020-08-08 07:33:50 ✨ [Relaychain] Imported #7623 (0xedee…cd52)
2020-08-08 07:33:54 💤 [Parachain] Idle (1 peers), best: #64 (0x6f4c…d715), finalized #0 (0xcf5c…5b75), ⬇ 10.2kiB/s ⬆ 7.3kiB/s
2020-08-08 07:33:54 💤 [Relaychain] Idle (4 peers), best: #7623 (0xedee…cd52), finalized #7621 (0x34ac…29f7), ⬇ 26.5kiB/s ⬆ 22.7kiB/s
2020-08-08 07:33:54 💔 Block announcement validation errored: UnknownBlock: 0x8c10…b49a
2020-08-08 07:33:55 ✨ [Relaychain] Imported #7624 (0x8c10…b49a)
2020-08-08 07:33:59 💤 [Parachain] Idle (1 peers), best: #64 (0x6f4c…d715), finalized #0 (0xcf5c…5b75), ⬇ 11.0kiB/s ⬆ 7.0kiB/s
2020-08-08 07:33:59 💤 [Relaychain] Idle (4 peers), best: #7624 (0x8c10…b49a), finalized #7621 (0x34ac…29f7), ⬇ 25.0kiB/s ⬆ 18.6kiB/s
2020-08-08 07:34:00 💔 Block announcement validation errored: UnknownBlock: 0x222f…bd3e
```

**Description**

On the latest cumulus parachain synchronization doesn't work well, periodically it holds with `UnknownBlock` errors.

**Comment by bkchr** [comment] 2020-08-08 11:48
Duplicate of: https://github.com/paritytech/cumulus/issues/147

**Closed by bkchr** 2020-08-08 11:48 UTC
