### ISSUE TITLE
Acala node stalled for an hour

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#1480] opened 2022-07-28 22:31 UTC
One of our Acala parachain stalled for an hour without outputting any logs and not syncing blocks. This is the logs:

```
"2022-07-28 17:53:04.295 WARN tokio-runtime-worker sync: [Parachain] 💔 Ignored block (#1526199 -- 0xcd53…4a3e) announcement from 12D3KooWKapuzLADXUrshtZnD3F13E2WEDr8eonZ23qJSvPXBuDy because all validation slots for this peer are occupied."
"2022-07-28 17:53:04.295 WARN tokio-runtime-worker sync: [Parachain] 💔 Ignored block (#1526199 -- 0xcd53…4a3e) announcement from 12D3KooWK8s8ohuxyStviiumydSBwKD6vUmqN9KZDrwonMvb2kNz because all validation slots for this peer are occupied."
"2022-07-28 16:58:27.640 INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (50 peers), best: #11361778 (0x7c55…629d), finalized #11361775 (0x89f7…9f0d), ⬇ 177.3kiB/s ⬆ 1.8kiB/s"
"2022-07-28 16:57:32.610 INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (50 peers), best: #11361778 (0x7c55…629d), finalized #11361775 (0x89f7…9f0d), ⬇ 43.8kiB/s ⬆ 1.2kiB/s"
```

[extract-2022-07-28T22_23_04.743Z.csv](https://github.com/paritytech/cumulus/files/9214590/extract-2022-07-28T22_23_04.743Z.csv)

**Comment by bkchr** [comment] 2022-07-28 22:36
Hmm. Do you have more statistics? What was the CPU usage?

**Comment by xlc** [comment] 2022-07-28 23:45
Just right before the stall

<img width="1472" alt="Screen Shot 2022-07-29 at 11 44 26 AM" src="https://user-images.githubusercontent.com/1201310/181655114-de398db3-9720-4908-9850-41e12fa1c202.png">
<img width="1494" alt="Screen Shot 2022-07-29 at 11 45 00 AM" src="https://user-images.githubusercontent.com/1201310/181655148-51b29b8b-9d9c-4531-a0d7-1aea38a58432.png">

**Comment by bkchr** [comment] 2022-07-29 09:37
Ty. AFAIR we already had a similar report at some point. Aka some node was not printing anything for an hour or similar, but I think this was in Polkadot. However, I can not find it. @koute do you maybe remember the issue? AFAIR we didn't fixed it/found something.

**Comment by ggwpez** [comment] 2022-07-29 09:38
Did the node react to RPC calls in that time?  
I had something in the past where just the stdout was getting messed up somehow. So the node itself worked fine, but could not print anymore.

**Comment by koute** [comment] 2022-07-29 10:09
@bkchr Hmmm.... Yes, I also have a vague feeling that I've seen something like this before, but unfortunately I don't remember the specifics off the top of my head.

This definitely looks strange. The iowait graph suggests the process was spending almost half of its time blocked on IO which is abnormal since we use async IO, and that AFAIK is only triggered by sync IO; the only place I can think of which uses sync IO is the logger, but that should never block as long as the other side of the stderr doesn't block. Also the CPU graph from the second image suggests that the CPU usage suddenly dropped, but the load average from the first image suggests that something suddenly started to burn the CPU. (@xlc Am I correct to assume that the "Total CPU %" is the CPU time **only** for your parachain process and *doesn't* include any other process on the system?)

So my educated guess would be that whatever was ingesting the logs from the node might have went into an infinite loop or something like that, which would explain both the node's behavior and also why the system-wide load average increased.

**Comment by koute** [comment] 2022-07-29 10:35
Also, a question, just in case: are you using RocksDB or ParityDB?

**Comment by ggwpez** [comment] 2022-07-29 11:21
I tested to clog the stdout on a syncing Polkadot node with `--log=trace` enabled but it keeps syncing, so clogged stdout does not seem to be a problem in general.  
Not sure if this could also be my linux. It probably printed a "broken pipe" at some point, but the log is too long to search.

**Comment by koute** [comment] 2022-07-29 11:25
> I tested to clog the stdout on a syncing Polkadot node with `--log=trace` enabled but it keeps syncing, so clogged stdout does not seem to be a problem in general. Not sure if this could also be my linux. It probably printed a "broken pipe" at some point, but the log is too long to search.

[The logs are printed out to stderr](https://github.com/paritytech/substrate/blob/9428b0ea492d405f320753fcd93bc59ebb3bf33b/client/tracing/src/logging/stderr_writer.rs#L90) so you might want to clog that up too. (:

**Comment by ggwpez** [comment] 2022-07-29 14:03
It indeed became an error after also clogging the stderr.  
So it could be related to slow log ingestion, although we dont have a way to currently verify this.  

A syslog could be posted if flushing takes longer than x minutes.  
@koute mentioned that the ingestor which stalls the Polkadot log could also be the one ingesting the syslog and then stall as well.  
But I think its worth a try; either it works and we have a way of detecting the problem, or it doesnt and there is no harm.

**Comment by xlc** [comment] 2022-07-31 23:04
It is rocks DB. The total CPU is user CPU + system CPU for this parachain node container.

**Comment by koute** [comment] 2022-08-08 06:23
So I'm almost certain that whatever was ingesting the logs from your container most likely stopped doing that (or simply deadlocked). I remember seeing this happen in the past at least once, however I don't remember what the root cause of it was.

Nevertheless, this isn't really a bug on our side, and as far as I'm concerned we're working correctly. We don't want to accidentally drop any potentially important logs because e.g. the other end of the stderr has a temporary hiccup writing to the disk, so our current behavior of blocking when that happens is what we want. The buffer sizes are generous enough that in normal cases this should never be a problem, unless, of course, this "temporary hiccup" is one hour long instead of one hundred milliseconds long, but in that case whatever's ingesting the stderr is horribly broken and should be fixed.

**Closed** 2022-08-08 08:35 UTC
