### ISSUE TITLE
`Storage root must match that calculated` right after runtime upgrade is executed in `test-parachain` with `pallet_scheduler`

### ISSUE THREAD

**Issue by ghzlatarev** [paritytech/cumulus#601] opened 2021-09-09 13:04 UTC
Hey guys, i'm trying to add governance with democracy pallet to our runtime and do a runtime upgrade. Configured `pallet_democracy` to use `pallet_scheduler` and I'm having difficulties with the latter.

Getting a `Storage root must match that calculated` error right after the runtime upgrade is executed. Either with `system.setCode` or `parachainSystem.authorizeUpgrade + parachainSystem.enactAuthorizedUpgrade`

Managed to Isolate the problem to `pallet_scheduler` because the same error appears if the runtime upgrade is done simply with sudo + scheduler. 

Here's a minimal reproducible example using the `test-parachain` from this repo with `rococo-local` relay chain. Forked from branch `polkadot-v0.9.9` 
https://github.com/ghzlatarev/cumulus/commit/9056176013e0b1b8bf04b46c64345ac4734bbeab

For the local testnet I use the following `polkadot-launch` config and polkadot with branch `release-v0.9.9`:

```
{
	"relaychain": {
		"bin": "../../Parity/polkadot/target/release/polkadot",
		"chain": "rococo-local",
			"nodes": [
					{
							"name": "alice",
							"wsPort": 9944,
							"port": 30444
					},
					{
							"name": "bob",
							"wsPort": 9955,
							"port": 30555
					},
					{
							"name": "charlie",
							"wsPort": 9966,
							"port": 30666
					},
					{
							"name": "dave",
							"wsPort": 9977,
							"port": 30777
					}
			],
			"genesis": {
					"runtime": {
							"runtime_genesis_config": {
									"parachainsConfiguration": {
											"config": {
													"validation_upgrade_frequency": 1,
													"validation_upgrade_delay": 1
											}
									}
							}
					}
			}
	},
	"parachains": [
			{
					"bin": "../../Parity-forks/cumulus/target/release/polkadot-collator",
					"id": "300",
					"balance": "1000000000000000000000",
					"nodes": [
							{
									"wsPort": 9999,
									"port": 31300,
									"name": "alice",
									"flags": ["--", "--execution=wasm"]
							},
							{
									"wsPort": 9989,
									"port": 31400,
									"name": "bob",
									"flags": ["--", "--execution=wasm"]
							}
					]
			}
	],
	"hrmpChannels": [
	],
	"types": {
	  	"Id": "[u8; 4]",
	  	"ChainId": "Id",
	  	"LaneId": "Id",
		"MessageNonce": "u64",
		"MessageId": "(Id, u64)",
		"MessageKey": {
			"lane_id": "LaneId",
			"nonce:": "MessageNonce"
		}
	},
	"finalization": false
}
```

Any tips on this would be appreciated. Currently i'm not sure if there's something wrong with my polkadot-launch config, or my runtime configuration, or there's an alternative way to do democracy without scheduler.

Thanks for the attention!

**Comment by al3mart** [comment] 2021-09-09 13:35
Have you used scheduler every time with SUDO `system.setCode()` ?

**Comment by al3mart** [comment] 2021-09-09 13:35
Have you used scheduler every time with SUDO `system.setCode()` ?

**Comment by ghzlatarev** [comment] 2021-09-09 13:41
Not sure what you mean by every time. 
But for this experiment I tried sudo and `system.setCode()` and it reproduced the same error, even on master branches.

![sudoschedule](https://user-images.githubusercontent.com/45011053/132696554-b219ca2a-2231-4a1b-b760-9550600db9b7.PNG)

Also tried `parachainSystem.authorizeUpgrade` + `parachainSystem.enactAuthorizedUpgrade`  for the same result

**Comment by al3mart** [comment] 2021-09-09 13:53
If you do the upgrade without using scheduler you have the same error ?

**Comment by ghzlatarev** [comment] 2021-09-09 13:54
No, just SUDO is fine. Never had a problem with it.

**Comment by JoshOrndorff** [comment] 2021-09-09 14:30
Moonriver recently had an issue doing an upgrade using democracy (which uses scheduler under the hood). I believe the upgrade was enacted at different blocks on the relay and on the para (off-by-one). Perhaps this is the same issue?

**Comment by al3mart** [comment] 2021-09-09 15:00
@JoshOrndorff I was looking for the report of that issue, but I can't find it. I think the conversation there can be valuable for @ghzlatarev

**Comment by bkchr** [comment] 2021-09-09 19:55
@ghzlatarev do you also have executed the `enactAuthorizedUpgrade` through the scheduler? If yes, don't do it.

The problem is that the ParachainSystem inherent isn't yet executed and that leads to the off by one error as mentioned by @JoshOrndorff

**Comment by ghzlatarev** [comment] 2021-09-09 20:03
Yes, for the experiment I executed `parachainSystem.enactAuthorizedUpgrade` with the scheduler. My thought was that the scheduler would also be used if called through the democracy pallets.
In the context of governance, am I supposed to be calling `authorizeUpgrade` through the democracy pallet, and then `enactAuthorizedUpgrade` some other way like with sudo ? Probably missing something here. because sudo will have to be removed at some point.

**Comment by bkchr** [comment] 2021-09-09 20:12
`enactAuthorizedUpgrade` can be executed by everybody, it doesn't require sudo.

**Comment by ghzlatarev** [comment] 2021-09-09 20:25
Oh I see. So yes `enactAuthorizedUpgrade` without scheduler executed the upgrade successfully. A couple of questions: 

1. Is using `authorizeUpgrade` with democracy, and `enactAuthorizedUpgrade` the canon/proper way of doing upgrades for now ?
2. Is the behavior of `setCode` and `enactAuthorizedUpgrade` with scheduler going to be changed/fixed in the future ?

Thank you very much for the attention!

**Comment by bkchr** [comment] 2021-09-09 20:32
> * Is using `authorizeUpgrade` with democracy, and `enactAuthorizedUpgrade` the canon/proper way of doing upgrades for now ?

Yes that is the proper way for now.

> * Is the behavior of `setCode` and `enactAuthorizedUpgrade` with scheduler going to be changed/fixed in the future ?

Yeah the plan is to fix this in the future.

**Comment by ghzlatarev** [comment] 2021-09-09 20:52
Great! Thanks again for the clarifications.

**Comment by bkchr** [comment] 2021-09-11 22:51
I'm going to close this issue, if you have other issues, please open a new one.

**Closed by bkchr** 2021-09-11 22:51 UTC

**Comment by JoshOrndorff** [comment] 2021-09-12 17:55
Is the issue about enactment with the scheduler being tracked anywhere?

**Comment by bkchr** [comment] 2021-09-12 21:24
https://github.com/paritytech/substrate/pull/9324

**Comment by wischli** [comment] 2021-09-15 13:35
> > * Is using `authorizeUpgrade` with democracy, and `enactAuthorizedUpgrade` the canon/proper way of doing upgrades for now ?
> 
> Yes that is the proper way for now.

1. Just to be sure: Is this preferred over `democracy > .system.setCode` for parachains?
2. Should `authorizeUpgrade` and `enachtAuthorizedUpgrade` be a batched democracy call or only `authorizeUpgrade` via democracy?

**Comment by bkchr** [comment] 2021-09-15 14:25
>     1. Just to be sure: Is this preferred over `democracy > .system.setCode` for parachains?

This would brick your chain.



>     2\. Should `authorizeUpgrade` and `enachtAuthorizedUpgrade` be a batched democracy call or only `authorizeUpgrade` via democracy?

This should not be batched! `authorizeUpgrade` needs to be done by democracy. `enactAuthorizedUpgrade` is a call that can be executed by everybody.
