### ISSUE TITLE
Too many siblings when block are not included

### ISSUE THREAD

**Issue by crystalin** [paritytech/cumulus#1624] opened 2022-09-14 00:00 UTC
When relaychain **validators do not include the block** (because of PoV taking time to download or because of the validator being too slow), the parachain collators will keep producing sibling blocks, and will ALL get stuck because they have **too many siblings**.

If a block is finally included, all the other collators won't import it because they will have "too many siblings", getting them stalled. 

This happens now almost at every runtime upgrade in some networks :(

I'm not sure what the solution is but here are some ideas:
1. Increasing the number of siblings to an absurd number
2. Using a LIFO queue for storing the siblings, allowing new siblings to be processed
3. Allowing blocks matching those marked "best" to be imported even if sibling limit reached
4. Dropping siblings when the "best" is increasing

(cc @bkchr )

**Comment by bkchr** [comment] 2022-09-14 04:43
Duplicate of https://github.com/paritytech/cumulus/issues/432

And there is also a pr to fix this.

**Closed** 2022-09-14 04:43 UTC
