### ISSUE TITLE
ED Statemint changes

### ISSUE THREAD

**Issue by gilescope** [paritytech/cumulus#924] opened 2022-01-20 01:00 UTC
Placeholder to remind us to either merge in previous SR->ED changes ( https://github.com/paritytech/cumulus/pull/867/ ) or ideally make collator be able to use either. (If we do merge 867 into the new release branch then we probably want to carry it over to the new release branch without it hitting master).

**Comment by gilescope** [comment] 2022-01-20 01:04
Looks like this is what we are after: https://github.com/paritytech/cumulus/pull/923/

**Comment by bkchr** [comment] 2022-01-20 07:26
Duplicate of https://github.com/paritytech/cumulus/issues/885

**Closed** 2022-01-20 07:26 UTC
