### ISSUE TITLE
DB corrupted: Corruption: Corrupted compressed block contents

### ISSUE THREAD

**Issue by abhath-labs** [paritytech/cumulus#1194] opened 2022-04-21 11:13 UTC
Syncing parachain to rococo generates the following error:

```
2022-04-20 16:47:13 [Relaychain] DB corrupted: Corruption: Corrupted compressed block contents: Snappy. Repair will be triggered on next restart    
2022-04-20 16:47:13 [Relaychain] Block import error: Database    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0xf70389c0893eb2603c86c087d5472bcdf63e401f9cd9d46e8ac4678009c652fb: consensus error: Import failed: Import failed: Database    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0x2474ce5dbf0075dd96a6af41b3d7e846473ce571ecae9b74d268d198294b8801: block has an unknown parent    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0xaf3e7e3e4429cf3dae316fa074d688d660c45eed5d18ad2cfa6a72ac87f4830f: block has an unknown parent    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0xcddc29180173f0024f5de514b5c5476260840dde0a09241b0ed031c54e2efb2e: block has an unknown parent    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0xe77146a356ccc0b422cc192d4eb9b6d956d5e6bed5f7ba6a2ebca873b659d7b3: block has an unknown parent    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0xdf3d7de4ab483214165a37667b1be4a405991fa669f7fbb3ac75b200fbc8e5b0: block has an unknown parent    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0x97e17ed1120a0e0e2835936cc9eb89457f15d7054d86f895ab1e655129975350: block has an unknown parent    
2022-04-20 16:47:13 [Relaychain] DB corrupted: Corruption: Corrupted compressed block contents: Snappy. Repair will be triggered on next restart    
2022-04-20 16:47:13 [Relaychain] Block import error: Database    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0xf70389c0893eb2603c86c087d5472bcdf63e401f9cd9d46e8ac4678009c652fb: consensus error: Import failed: Import failed: Database    
2022-04-20 16:47:13 [Relaychain] 💔 Error importing block 0x3784e3a954b95f9c478720a7a0bb6d1f343301b673c5bb67cef351482f98790f: block has an unknown parent    
2022-04-20 16:47:13 [Relaychain] DB corrupted: Corruption: Corrupted compressed block contents: Snappy. Repair will be triggered on next restart    
2022-04-20 16:47:13 [Relaychain] Block import error: Database 
```

Startup command used
```
./target/release/parachain \
--alice \
--collator \
--force-authoring \
--chain rococo-local-parachain-2000-raw.json \
--base-path /tmp/parachain/alice \
--port 40333 \
--ws-port 9944 \
--rpc-port 9979 --rpc-cors all --discover-local \
--rpc-external --rpc-methods=unsafe \
-- \
--execution wasm \
--chain rococo.json
```

Using the latest rococo.json from https://github.com/paritytech/polkadot/blob/master/node/service/res/rococo.json

The error goes away after some time but syncing does not happen (0 bps)
```

2022-04-20 16:49:45 [Parachain] 💤 Idle (0 peers), best: #0 (0x0626…9b5d), finalized #0 (0x0626…9b5d), ⬇ 0 ⬆ 0    
2022-04-20 16:49:45 [Relaychain] ⚙️  Syncing  0.0 bps, target=#531880 (1 peers), best: #722 (0x6452…e6ea), finalized #512 (0xd1b3…6a0a), ⬇ 10.0kiB/s ⬆ 10.1kiB/s    
2022-04-20 16:49:50 [Parachain] 💤 Idle (0 peers), best: #0 (0x0626…9b5d), finalized #0 (0x0626…9b5d), ⬇ 0 ⬆ 0    
2022-04-20 16:49:50 [Relaychain] 💤 Idle (0 peers), best: #722 (0x6452…e6ea), finalized #512 (0xd1b3…6a0a), ⬇ 7.2kiB/s ⬆ 7.5kiB/s    
2022-04-20 16:49:55 [Parachain] 💤 Idle (0 peers), best: #0 (0x0626…9b5d), finalized #0 (0x0626…9b5d), ⬇ 0 ⬆ 0    
2022-04-20 16:49:55 [Relaychain] 💤 Idle (0 peers), best: #722 (0x6452…e6ea), finalized #512 (0xd1b3…6a0a), ⬇ 9.0kiB/s ⬆ 9.0kiB/s    
2022-04-20 16:50:00 [Parachain] 💤 Idle (0 peers), best: #0 (0x0626…9b5d), finalized #0 (0x0626…9b5d), ⬇ 0 ⬆ 0    
2022-04-20 16:50:00 [Relaychain] ⚙️  Syncing  0.0 bps, target=#531883 (1 peers), best: #722 (0x6452…e6ea), finalized #512 (0xd1b3…6a0a), ⬇ 9.7kiB/s ⬆ 10.3kiB/s    
2022-04-20 16:50:05 [Parachain] 💤 Idle (0 peers), best: #0 (0x0626…9b5d), finalized #0 (0x0626…9b5d), ⬇ 0 ⬆ 0    
2022-04-20 16:50:05 [Relaychain] ⚙️  Syncing  0.0 bps, target=#531883 (1 peers), best: #722 (0x6452…e6ea), finalized #512 (0xd1b3…6a0a), ⬇ 8.2kiB/s ⬆ 8.4kiB/s    
```

Already tried purging the chain for a fresh start but issue repeats everytime.
using polkadot v0.9.18
works locally with rococo-local, issue appears only when syncing with rococo

**Comment by bkchr** [comment] 2022-04-22 06:36
Duplicate of: https://github.com/paritytech/substrate/issues/11222

**Closed by bkchr** 2022-04-22 06:36 UTC
