### ISSUE TITLE
duplicated polkadot-parachain causing troubles

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#1815] opened 2022-11-07 10:11 UTC
https://github.com/paritytech/polkadot/blob/40aefb4ac396bcd098755c6d57dac7b284a343e7/parachain/Cargo.toml#L2
https://github.com/paritytech/cumulus/blob/ca213eaa4968b63e88ef604849341e12b4e0886c/polkadot-parachain/Cargo.toml#L2

they have same name and causing cargo to be confused when I have path override

**Comment by bkchr** [comment] 2022-11-07 11:10
Duplicate of: https://github.com/paritytech/cumulus/issues/1753

**Closed by bkchr** 2022-11-07 11:10 UTC
